# Generated by Django 5.2.8 on 2026-07-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Renseigné pour les tissus : sert à calculer le prix au m².', max_digits=5, null=True, verbose_name='Surface (m²)'),
        ),
    ]
