# Generated by Django 5.2.8 on 2026-07-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_area_sqm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='area_sqm',
        ),
        migrations.AddField(
            model_name='product',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Renseigné pour les tissus : sert à calculer le prix au mètre.', max_digits=5, null=True, verbose_name='Longueur (m)'),
        ),
    ]
